### PR TITLE
bolus edits

### PR DESCRIPTION
**Pull request by jebeck**
Here are my edits in response to your feedback today @darinkrauss Let me know if they are an improvement or not :)

Also just looking to see if I've truly duplicated everything from @gniezen's #6...

### CODE REVIEW

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uelAlTna&#x2F;15-data-model-updates-to-bolus-docs-from-feedback"> [data-model] updates to bolus docs from feedback</a>

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uelAlTna&#x2F;15-data-model-updates-to-bolus-docs-from-feedback"> [data-model] updates to bolus docs from feedback</a>

**Comment by darinkrauss** [comment]
LGTM :shipit:

**Comment by jebeck** [comment]
Everything from #6 is covered, so closing that as well.

**Pull request merged**
